[phases.setup]
nixPkgs = ["...", "php83", "php83Extensions.pdo_pgsql", "php83Extensions.mbstring", "php83Extensions.session"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'PHP app ready for deployment'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/"
